# The value of the TERM environment variable to set
term xterm-kitty

# Font
font_family      Fantasque Sans Mono
italic_font      auto
bold_font        auto
bold_italic_font auto

# Font size (in pts)
font_size        14.0

# Shell
shell /usr/bin/zsh

enable_audio_bell no
background_opacity 0.95


# BEGIN_KITTY_THEME
# Broadcast
include current-theme.conf
# END_KITTY_THEME